config/routes.rb
Tzm::Application.routes.draw do
  devise_for :users
  resources :users, :path => 'u' do
    member do
      put 'join_chapter/:chapter_id', :action => :join_chapter, :as => 'join_chapter'
    end
  end

  resources :coordinators, :only => [:new, :create, :destroy]
  resources :feedbacks, :path => 'feedback', :except => [:destroy]
  
  resources :chapters, :except => [:destroy] do
    collection do
      get :select_country_for_new
      get :select_territory_for_new
    end
    member do
      put "links/:link_id", :action => :update_link, :as => :link_for
      post :links, :action => :create_link, :as => :new_link_for
    end
  end
  
  resources :links
  resources :tasks
  resources :events
  resources :locations, :only => [:index, :show, :new, :create]

  resources :site_options, :only => [:index,:edit,:update]
  
  pages = ['protocols',"home"]

  pages.each do |page|
    get page, :to => 'pages#show', :uri => page
    get page+'/edit', :to => 'pages#edit', :uri => page, :as => "edit_#{page}"
    put page, :to => 'pages#update', :uri => page
  end
  
  root :to => "pages#show", :uri => "home"

  get "/:chapter_name", :controller => :chapters, :action => :show, :as => 'chapter'
  get "/:chapter_name/edit", :controller => :chapters, :action => :edit, :as => 'edit_chapter'
  put "/:chapter_name", :controller => :chapters, :action => :update, :as => 'chapter'
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :taskable, :polymorphic => true
  has_and_belongs_to_many :users

  def self.valid_states
    %w(new in_progress resolved closed rejected)
  end

  def self.valid_priorities
    %w(low normal high urgent)
  end

  attr_accessible :status, :priority, :category, :subject, :description, :starts_at, :due_at, :percent_complete

  validates :status,           :presence => true, :inclusion => {:in => valid_states}
  validates :priority,         :presence => true, :inclusion => {:in => valid_priorities}
  validates :category,         :presence => true, :length => {:maximum => 255 }
  validates :subject,          :presence => true, :length => {:maximum => 255 }
  validates :description,      :presence => true, :length => {:maximum => 4096}
  validates :starts_at,        :presence => true
  validates :percent_complete, :presence => true, :inclusion => {:in => 0..100}
  validates :taskable,         :presence => true
  
  def self.find_new
    find_all_by_status :new
  end

  def self.find_in_progress
    find_all_by_status :in_progress
  end

  def self.find_resolved
    find_all_by_status :resolved
  end

  def self.find_closed
    find_all_by_status :closed
  end

  def self.find_rejected
    find_all_by_status :rejected
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  load_and_authorize_resource

  before_filter :only => [:new, :create] do |controller|
    controller.load_polymorphic :taskable
  end
  
  def index
    @tasks = @tasks.search(index_params)
  end

  def show; end

  def new; end

  def edit; end

  def create
    @task.save!
    redirect_to @task, :notice => 'Task created successfully'
  rescue ActiveRecord::RecordInvalid
    render :new
  end

  def update
    @task.update_attributes! params[:task]
    redirect_to @task, :notice => 'Task update successfully'
  rescue ActiveRecord::RecordInvalid
    render :edit
  end

  def destroy
    @task.destroy
    redirect_to Task, :notice => 'Task removed successfully'
  end
end

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= link_to 'Show', task %></td>
    <td><%= link_to 'Edit', edit_task_path(task) %></td>
    <td><%= link_to 'Destroy', task, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>