config/routes.rb
Tzm::Application.routes.draw do
  devise_for :users
  resources :users, :path => 'u' do
    member do
      put 'join_chapter/:chapter_id', :action => :join_chapter, :as => 'join_chapter'
    end
  end

  resources :coordinators, :only => [:new, :create, :destroy]
  resources :feedbacks, :path => 'feedback', :except => [:destroy]
  
  resources :chapters, :except => [:destroy] do
    collection do
      get :select_country_for_new
      get :select_territory_for_new
    end
    member do
      put "links/:link_id", :action => :update_link, :as => :link_for
      post :links, :action => :create_link, :as => :new_link_for
    end
  end
  
  resources :links
  resources :tasks
  resources :events
  resources :locations, :only => [:index, :show, :new, :create]

  resources :site_options, :only => [:index,:edit,:update]
  
  pages = ['protocols',"home"]

  pages.each do |page|
    get page, :to => 'pages#show', :uri => page
    get page+'/edit', :to => 'pages#edit', :uri => page, :as => "edit_#{page}"
    put page, :to => 'pages#update', :uri => page
  end
  
  root :to => "pages#show", :uri => "home"

  get "/:chapter_name", :controller => :chapters, :action => :show, :as => 'chapter'
  get "/:chapter_name/edit", :controller => :chapters, :action => :edit, :as => 'edit_chapter'
  put "/:chapter_name", :controller => :chapters, :action => :update, :as => 'chapter'
end

app/models/coordinator.rb
class Coordinator < ActiveRecord::Base
  attr_accessible :user, :chapter

  belongs_to :user
  belongs_to :chapter

  before_validation :set_chapter_of_user, :if => 'chapter.nil?'

  validates :user,    :presence => true
  validates :chapter, :presence => true

  def set_chapter_of_user
    self.chapter = self.user.chapter unless self.user.nil?
  end
end

app/controllers/coordinators_controller.rb
class CoordinatorsController < ApplicationController
  load_and_authorize_resource
  
  def new; end

  def create
    @coordinator.user    = User.find_by_id params[:coordinator][:user_id]
    @coordinator.chapter = Chapter.find_by_id params[:coordinator][:chapter_id]
    @coordinator.save!
    redirect_to @coordinator.chapter, :notice => "Coordinator created successfully"
  rescue ActiveRecord::RecordInvalid
    render :new
  end

  def destroy
    @coordinator.destroy
    redirect_to chapter_url(@coordinator.chapter), :notice => "Coordinator removed successfully"
  end
end

app/views/coordinators/_form.html.erb
<%= form_for @coordinator do |f| %>
  <%= f.error_messages %>

  <div class="field">
    <%= f.label :members %>
    <%= f.collection_select :user_id, User.all, :id, :name_with_username %>
  </div>

  <div class="field">
    <%= f.label :chapters %>
    <%= f.collection_select :chapter_id, Chapter.all, :id, :name %>
  </div>

  <div class="actions">
    <%= f.submit "Create" %>
  </div>
<% end %>

app/views/coordinators/new.html.erb
<% title "New Coordinator" %>
<% page_class 'form' %>
<% page_head_class 'form' %>
<% simple_page_head "New Coordinator" %>

<%= render 'form' %>

app/views/coordinators/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_coordinator_path(@coordinator) %> |
<%= link_to 'Back', coordinators_path %>