config/routes.rb
Tzm::Application.routes.draw do
  devise_for :users
  resources :users, :path => 'u' do
    member do
      put 'join_chapter/:chapter_id', :action => :join_chapter, :as => 'join_chapter'
    end
  end

  resources :coordinators, :only => [:new, :create, :destroy]
  resources :feedbacks, :path => 'feedback', :except => [:destroy]
  
  resources :chapters, :except => [:destroy] do
    collection do
      get :select_country_for_new
      get :select_territory_for_new
    end
    member do
      put "links/:link_id", :action => :update_link, :as => :link_for
      post :links, :action => :create_link, :as => :new_link_for
    end
  end
  
  resources :links
  resources :tasks
  resources :events
  resources :locations, :only => [:index, :show, :new, :create]

  resources :site_options, :only => [:index,:edit,:update]
  
  pages = ['protocols',"home"]

  pages.each do |page|
    get page, :to => 'pages#show', :uri => page
    get page+'/edit', :to => 'pages#edit', :uri => page, :as => "edit_#{page}"
    put page, :to => 'pages#update', :uri => page
  end
  
  root :to => "pages#show", :uri => "home"

  get "/:chapter_name", :controller => :chapters, :action => :show, :as => 'chapter'
  get "/:chapter_name/edit", :controller => :chapters, :action => :edit, :as => 'edit_chapter'
  put "/:chapter_name", :controller => :chapters, :action => :update, :as => 'chapter'
end

app/models/user.rb
class User < ActiveRecord::Base
  extend Index
  index do |i|
    i.search :name, :username
    i.sort :name, :username
    i.default_sort :username, :asc
    i.paginate 20
  end

  attr_accessible :name, :username, :email, :password

  devise :database_authenticatable, :rememberable, :recoverable, :trackable, :validatable

  belongs_to :chapter
  has_many :coordinators
  has_and_belongs_to_many :tasks

  validates :name,     :presence => true, :length => {:maximum => 50}
  validates :username, :presence => true, :uniqueness => true, :length => {:maximum => 30}

  def coordinator?
    coordinators.any?
  end

  def name_with_username
    "#{name} (#{username})"
  end

  def location
    unless self.chapter.nil?
      chapter.geographic_location
    else
      GeographicLocation.new(:name => "Unknown")
    end
  end

  def is_admin!
    update_attribute :admin, true
  end

  def is_not_admin!
    update_attribute :admin, false
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  helper_method :sort_column, :sort_direction

  rescue_from ActiveRecord::RecordNotFound do
    redirect_to users_url
    flash[:error] = "User not found"
  end

  def index
    @users = User.search(index_params)
  end

  def show; end
  def new;  end
  def edit; end

  def create
    @user.save!
    flash[:notice] = "User created successfully"
    redirect_to (user_signed_in? ? @user : new_user_session_path)
  rescue ActiveRecord::RecordInvalid
    render :new
  end

  def update
    @user.update_attributes! params[:user]
    flash[:notice] = "User updated successfully"
    redirect_to @user
  rescue ActiveRecord::RecordInvalid
    render :edit
  end

  def join_chapter
    chapter = Chapter.find params[:chapter_id]
    @user.update_attribute :chapter, chapter
    redirect_to chapter, :notice => "You have joined the #{chapter.name} chapter"
  rescue ActiveRecord::RecordNotFound
    redirect_to Chapter, :alert => "Chapter does not exist"
  end

private

  def sort_column
    User.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/views/users/_users.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>

<center><%= will_paginate @users %></center>
<table>
  <tr>
    <th><%= sortable "name" %></th>
    <th><%= sortable "username" %></th>
    <th>Chapter</th>
    <th>Location</th>
    <% if can? :update, User %>
      <th>Edit</th>
    <% end %>
  </tr>
  <% for user in @users %>
    <tr>
      <td><%= link_to user.name, user_path(user) %></td>
      <td><%= user.username %></td>
      <td><%= user.chapter.nil? ? "No Chapter" : user.chapter.name %></td>
      <td><%= user.location.self_and_parent_name %></td>
      <% if can? :update, User %>
        <td><%= link_to "Edit", edit_user_path(user) %></td>
      <% end %>
    </tr>
  <% end %>
</table>
<center><%= will_paginate @users %></center>

app/views/users/edit.html.erb
<% title 'Update Profile' %>
<% page_class 'form' %>

<%= content_for :page_head, content_tag(:h1, "Update Profile") %>
<%= form_for @user do |f| %>
  <%= f.error_messages %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :chapter %>
    <%= f.collection_select :chapter_id, Chapter.all, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit "Save" %>
  </div>
<% end %>

app/views/users/index.html.erb
<% title 'Members' %>
<% page_class 'one-column' %>

<%= content_for :page_head, content_tag(:h1, "ZM Members Index") %>

<%= form_tag users_path, :method => :get, :id => "users_search" do %>
<div id="search-container">
  <div>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag ">", :name => nil %>
  </div>
</div>
<div id="users"><%= render 'users' %></div>
<% end %>

app/views/users/index.js.erb
$("#users").html("<%= escape_javascript(render("users")) %>");

app/views/users/new.html.erb
<% title (current_user.try(:admin?) ? 'Create new member' : 'Sign Up') %>
<% page_class 'form' %>
<% page_head_class 'form' %>

<%= content_for(:page_head, content_tag(:h1, current_user.try(:admin?) ? "Create Member" : "Sign Up")) %>

<%= form_for @user do |f| %>
  <%= f.error_messages %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <% text = (current_user.try(:admin?) ? 'Create' : 'Sign Up') %>
    <%= f.submit text %>
  </div>
<% end %>

app/views/users/show.html.erb
<% title @user.username, false %>
<% page_class 'onecolumn' %>
<% page_head_class 'userpage' %>

<%= content_for :page_head do %>
  <h1 class="avatared">
    <span class="tooltipped">
      <a href="http://gravatar.com/emails/">
        <%= gravatar_for @user, :gravatar => {:size => 48} %>
      </a>
    </span>
    <%= @user.username %>
    <em>(<%= @user.name %>)</em>
  </h1>
  <ul class="actions">
    <% if user_signed_in? and current_user == @user %>
      <li class="text">This is you!</li>
      <li><%= link_to content_tag(:span, "Edit Your Profile"), edit_user_path(current_user) %></li>
      <% if @user.chapter.nil? %>
        <li>or <%= link_to content_tag(:span, "Join a Chapter"), chapters_path %></li>
      <% end %>
    <% end %>
  </ul>
<% end %>