config/routes.rb
Tzm::Application.routes.draw do
  devise_for :users
  resources :users, :path => 'u' do
    member do
      put 'join_chapter/:chapter_id', :action => :join_chapter, :as => 'join_chapter'
    end
  end

  resources :coordinators, :only => [:new, :create, :destroy]
  resources :feedbacks, :path => 'feedback', :except => [:destroy]
  
  resources :chapters, :except => [:destroy] do
    collection do
      get :select_country_for_new
      get :select_territory_for_new
    end
    member do
      put "links/:link_id", :action => :update_link, :as => :link_for
      post :links, :action => :create_link, :as => :new_link_for
    end
  end
  
  resources :links
  resources :tasks
  resources :events
  resources :locations, :only => [:index, :show, :new, :create]

  resources :site_options, :only => [:index,:edit,:update]
  
  pages = ['protocols',"home"]

  pages.each do |page|
    get page, :to => 'pages#show', :uri => page
    get page+'/edit', :to => 'pages#edit', :uri => page, :as => "edit_#{page}"
    put page, :to => 'pages#update', :uri => page
  end
  
  root :to => "pages#show", :uri => "home"

  get "/:chapter_name", :controller => :chapters, :action => :show, :as => 'chapter'
  get "/:chapter_name/edit", :controller => :chapters, :action => :edit, :as => 'edit_chapter'
  put "/:chapter_name", :controller => :chapters, :action => :update, :as => 'chapter'
end

app/views/shared/_debug.html.erb
<% if Rails.env.development? %>
  <% css 'debug' %>
  <div id="debug">
    <div class="header">
      Debug Console
    </div>
    <div style="width:100%; overflow:hidden">
      <div class="subheader">
        Models
      </div>
      <div class="subheader">
        Controllers
      </div>
      <div class="subheader">
        Other
      </div>
    </div>
    <div style="width:100%">
      <div class="console left">
        <%= yield(:debug_model) %>
      </div>
      <div class="console center">
        <%= yield(:debug_controller) %>
      </div>
      <div class="console right">
        <%= yield(:debug_other) %>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(object.errors.count, 'error') %>
      prohibited this resource from being saved:
    </h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feedback.html.erb
<%= create_link FeedbackRequest, "Feedback", :class => "feedback" %>

app/views/shared/_footer.html.erb
<ul>
  <li><a href="http://www.thezeitgeistmovement.com">Zeitgeist Movement</a></li>
  <li><a href="http://www.thevenusproject.com">Venus Project</a></li>
  <li><a href="http://www.zmdev.net">Developers</a></li>
</ul>

app/views/shared/_header.html.erb
<% if user_signed_in? && current_user.admin? %>
  <a class="manager" href="#">Manager</a>
  <div id="control-container">
    <% if current_user.admin? %>
      <div class="panel admin">
        <div>
          <ul class="button-bar">
            <li><%= link_to 'Create Member', new_user_path %></li>
            <li><%= link_to 'Create Coordinator', new_coordinator_path %></li>
            <li><%= link_to 'Site Options', site_options_path %></li>
            <li><%= link_to 'View Feedback', feedback_requests_path %></li>
            <%= yield(:admin_control_panel) %>
          </ul>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

<div class="header">
  <div class="auth">
  <% if user_signed_in? %>
    <span class="logged-in-as">You are signed in as <%= link_to current_user.name, user_path(current_user) %></span>
    <span class="account">
      <%= link_to "My Profile", user_path(current_user) %> |
      <%= link_to "Sign Out", destroy_user_session_path %>
    </span>
  <% else %>
    <span class="account">
      <%= link_to "Sign In", new_user_session_path %> |
      <%= link_to "Register", new_user_path %>
    </span>
  <% end %>
  </div>
  <div class="nav">
    <a href="/"><span class="logo"><em>ZM</em>Chapters</span></a>
    <ul class="main">
      <li><%= link_to "Chapters", chapters_path %></li>
      <li><%= link_to "Members", users_path %></li>
      <li><%= link_to "Events", events_path %></li>
    </ul>
    <ul>
      <li><%= link_to "Protocols", protocols_path %></li>
    </ul>
  </div>
</div>

app/views/shared/_map.html.erb
<%= content_for :js do %>
  <script type="text/javascript" src="http://www.openlayers.org/api/OpenLayers.js"></script>
  <script type="text/javascript">
    $(function() {
      map = new OpenLayers.Map("map", {
        <% if @map[:events] %>
          eventListeners: {
            "moveend": onMove
          }
        <% end %>
      });
      map.addLayer(new OpenLayers.Layer.OSM());
      latlng = new OpenLayers.LonLat(<%= "#{@map[:lng]}, #{@map[:lat]}" %>);
      map.setCenter(latlng, <%= @map[:zoom] %>);

      // Markers
      var markers = new OpenLayers.Layer.Markers("Markers");

      var size = new OpenLayers.Size(21,25);
      var offset = new OpenLayers.Pixel(-(size.w/2), -size.h);
      var icon = new OpenLayers.Icon('http://www.openlayers.org/dev/img/marker.png',size,offset);
      
      <% @map[:markers].each do |m| %>
        markers.addMarker(new OpenLayers.Marker(new OpenLayers.LonLat(<%= "#{m.lng}, #{m.lat}" %>), icon.clone()));
      <% end %>
      map.addLayer(markers);
    });
  </script>
<% end %>
<div id="map"></div>

app/views/shared/_scheduler.html.erb
<% css 'dhtmlxscheduler' %>
<% js 'dhtmlxscheduler' %>

<div id="chapter_scheduler" class="dhx_cal_container">
  <div class="dhx_cal_navline">
    <div class="dhx_cal_prev_button">&nbsp;</div>
    <div class="dhx_cal_next_button">&nbsp;</div>
    <div class="dhx_cal_today_button"></div>
    <div class="dhx_cal_date"></div>
    <div class="dhx_cal_tab" name="day_tab" style="right:204px;"></div>
    <div class="dhx_cal_tab" name="week_tab" style="right: 140px;"></div>
    <div class="dhx_cal_tab" name="month_tab" style="right: 76px;"></div>
  </div>
  <div class="dhx_cal_header">
  </div>
  <div class="dhx_cal_data">
  </div>
</div>

<%= content_for :js do %>
  <script type="text/javascript">
    $(function() {
      scheduler.config.multi_day = true;
      scheduler.config.xml_date = "%Y-%m-%d %H:%i";
      scheduler.init('chapter_scheduler', null, 'week');
      scheduler.load('/events.xml');
    });
  </script>
<% end %>